# Generated by Django 3.1.4 on 2020-12-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('vod', models.CharField(max_length=100)),
                ('oddal_kt2', models.BooleanField()),
                ('oddal_kt3', models.BooleanField()),
                ('oddal_kt5', models.BooleanField()),
                ('oddal_kt6', models.BooleanField()),
                ('oddal_kt7', models.BooleanField()),
                ('oddal_kt8', models.BooleanField()),
                ('oddal_kt9', models.BooleanField()),
                ('tocke_kt2', models.IntegerField()),
                ('tocke_kt3', models.IntegerField()),
                ('tocke_kt5', models.IntegerField()),
                ('tocke_kt6', models.IntegerField()),
                ('tocke_kt8', models.IntegerField()),
                ('tocke_kt9', models.IntegerField()),
                ('beseda_kt7', models.CharField(max_length=100)),
            ],
        ),
    ]
