# Generated by Django 3.1.4 on 2020-12-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='oddal_kt2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oddal_kt3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oddal_kt5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oddal_kt6',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oddal_kt7',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oddal_kt8',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oddal_kt9',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tocke_kt2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tocke_kt3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tocke_kt5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tocke_kt6',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tocke_kt8',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tocke_kt9',
        ),
    ]
