# Generated by Django 3.1.4 on 2020-12-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0003_auto_20201229_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='beseda_kt7',
        ),
        migrations.AddField(
            model_name='user',
            name='oddal_kt2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='oddal_kt3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='oddal_kt5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='oddal_kt6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='oddal_kt7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='oddal_kt8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='oddal_kt9',
            field=models.BooleanField(default=False),
        ),
    ]
