# Generated by Django 3.1.4 on 2020-12-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0004_auto_20201229_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashh',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
