# Generated by Django 3.1.4 on 2020-12-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0005_user_hashh'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='beseda_kt7',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='tocke_kt2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tocke_kt3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tocke_kt5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tocke_kt6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tocke_kt8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tocke_kt9',
            field=models.IntegerField(default=0),
        ),
    ]
