# Generated by Django 3.1.4 on 2020-12-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0006_auto_20201230_0857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
