# Generated by Django 3.1.4 on 2020-12-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0007_auto_20201230_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oddal_kt1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='oddal_kt4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sum_tocke',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tocke_kt1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tocke_kt4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tocke_kt7',
            field=models.IntegerField(default=0),
        ),
    ]
